export const SET_FURNITURE_QUANTITY = "SET_FURNITURE_QUANTITY";
export const LOAD_FURNITURES = "LOAD_FURNITURES"
export const FURNITURES_LOADING = "FURNITURES_LOADING"
export const FURNITURES_FAILED = "FURNITURES_FAILED"

export const ADD_COMMENT = "ADD_COMMENT"
export const LOAD_COMMENTS = "LOAD_COMMENTS"
export const COMMENTS_LOADING = "COMMENTS_LOADING"
export const COMMENTS_FAILED = "COMMENTS_FAILED"

export const APPLY_COUPON = "APPLY_COUPON"
export const CHANGE_SHIPPING_COST = "CHANGE_SHIPPING_COST"
export const FINISH_CHECKOUT = "FINISH_CHECKOUT"

export const LOG_IN = "LOG_IN"
export const CREATE_USER = "CREATE_USER"

export const OPEN_DEAL_MODAL = "OPEN_DEAL_MODAL"
export const CLOSE_DEAL_MODAL = "CLOSE_DEAL_MODAL"