export const ADD_SINGLE_FURNITURE = "ADD_SINGLE_FURNITURE";
export const REMOVE_SINGLE_FURNITURE = "REMOVE_SINGLE_FURNITURE";
export const SET_MULTIPLE_FURNITURES = "SET_MULTIPLE_FURNITURES";
export const DELETE_FURNITURES = "DELETE_FURNITURES";