export const SET_FURNITURE_QUANTITY = "SET_FURNITURE_QUANTITY";
export const LOAD_FURNITURES = "LOAD_FURNITURES"
export const FURNITURES_LOADING = "FURNITURES_LOADING"
export const FURNITURES_FAILED = "FURNITURES_FAILED"